apiVersion: v1
kind: ReplicationController
metadata: 
  name: rc1
spec:
  replicas: 3
  selector: 
    type: podsAPP1
  template:
    metadata:
      name: pods-3
      labels: 
        type: podsAPP1
    spec:
      containers:
        - name: con-for-app1
          image: nginx

