affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      weight: 1
      preference:
        matchExpressions:
        - key: <key>
          operator: In
          values:
          - <value>
