apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds1
spec:
  selector: 
   matchLabels:
     type: front
  template:
    metadata:
      labels:
        type: front
    spec:
      containers:
        - name: nginx
          image: nginx                   