# Role and RoleBinding

# 1) Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: role-1
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
  resourceName: pod-1
---
# 2) RoleBinding 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-1
  namespace: default
subjects:
- kind: User
  name: khattab       
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role-1
  apiGroup: rbac.authorization.k8s.io
