apiVersion: batch/v1
kind: CronJob
metadata:
  name: cj-task
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 3  # default 3
  failedJobsHistoryLimit: 1     # default 1     
  jobTemplate:
    spec:
      completions: 5       # default 1
      parallelism: 2       # default 1
      template:
        spec:
          containers:
            - name: nginx 
              image: nginx
              command: ["echo", "Task Completed"]
          restartPolicy: Never   # default allow
---